### ISSUE TITLE
Support custom ObjectFactory

### ISSUE THREAD

**Issue by enedzvetsky** [j-easy/easy-random#341]
We use custom class instantiators in our project. So some our project classes don't have a default constructor and these objects can be created only from these instantiators.
I would like to override method io.github.benas.randombeans.ObjectFactory#createNewInstance and inject our custom instantiators.
1. Unfortunately, class ObjectFactory is not public
2. EnhancedRandomBuilder doesn't have ObjectFactory customization.

**Comment by benas** [comment]
This is one of the things I wanted to do in a major release: making every behaviour overridable instead of configurable. See my comment [here](https://github.com/benas/random-beans/issues/149#issuecomment-264844185).

**Comment by benas** [comment]
A new interface `org.jeasy.random.api.ObjectFactory` has been added in order to allow you customize object creation. It can be used as follows:

```java
EasyRandomParameters parameters = new EasyRandomParameters()
        .objectFactory(new MyObjectFactory());

EasyRandom easyRandom = new EasyRandom(parameters);
```

You can find an example [here](https://github.com/j-easy/easy-random/blob/master/easy-random-core/src/test/java/org/jeasy/random/parameters/ObjectFactoryTests.java) and try it with version `4.0.0.RC1`. Please note that the project has been renamed to Easy Random. Hence, the `groupId` and `artifactId` have changed. I invite you to check the [release note](https://github.com/j-easy/easy-random/releases/tag/easy-random-4.0.0.RC1) which contains a migration guide.

I'm closing this issue for now, but please do not hesitate to provide your feedback by adding a comment here.
