### ISSUE TITLE
Seed property is not settable

### ISSUE THREAD

**Issue by usmanovbf** [j-easy/easy-random#357]
Code to execute bug:
`EasyRandomParameters parameters = new EasyRandomParameters().seed(99).randomizationDepth(99);
EasyRandom random = new EasyRandom(parameters);
random.setSeed(99);`

Expected seed: 99
Actual seed: 

![6c858e0738](https://user-images.githubusercontent.com/1210553/67623602-7dd47780-f827-11e9-9143-4ad55efc9182.png)

**Comment by benas** [comment]
Since `EasyRandom` extends `java.util.Random`, it inherits this behaviour. Here is an example with plain `java.util.Random`:

```java
public class Test357 {

	@Test
	public void test() {
		java.util.Random random = new java.util.Random();
		random.setSeed(99);
		System.out.println("r = " + random);
	}
}
```

![Screenshot 2019-10-26 at 19 35 20](https://user-images.githubusercontent.com/1210553/67623633-e885b300-f827-11e9-9805-98ce1bcc395b.png)

From the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/util/Random.html#setSeed-long-) of `java.util.Random#setSeed`:

```
The method setSeed is implemented by class Random by atomically updating the seed to
 (seed ^ 0x5DEECE66DL) & ((1L << 48) - 1)
```
