### ISSUE TITLE
@Size annotation for strings inside Collection not working

### ISSUE THREAD

**Issue by zougamohamed** [j-easy/easy-random#372]
Hello there,

I have a Set of Strings in my bean, and when generating a random instance, the generated strings don't respect the annotations.

 ` private Set<@Size(min = 1, max = 10) String> listOfStrings;`

Thanks

**Comment by benas** [comment]
What a good catch! Indeed, the `@Size` annotation is not honored in this case.

However, due to type erasure, I'm not sure it is possible to introspect the annotation on a generic type. I added a note about this limitation in the [known limitations](https://github.com/j-easy/easy-random/wiki/known-limitations#bean-validation) section of the wiki. You can use a custom randomizer for this kind of fields.

Thank you for reporting this anyway!
