### ISSUE TITLE
randomization of nested (recursive) object

### ISSUE THREAD

**Issue by roborobo2** [j-easy/easy-random#384]
There is problem with recursive Objects randomization due to cache.

object:

class A {
    protected String id;
    protected String name;
    protected A child;
    protected List<B'> property;
}

class B {
    String prop1;
    String prop2;
}

used config
EasyRandomParameters().randomizationDepth(2)
.collectionSizeRange(2, 2)
                .objectPoolSize(2);

even with depth=2 is still A.property.prop1 =null and A.property.prop2 =null because is set to null when is processing A.child.propery.propX due to depth limit and is stored to cache. When A.property is processing, cached value with nulls is taken

generated object
![image](https://user-images.githubusercontent.com/2378631/72423170-1c67d900-3784-11ea-96d9-6691e62af2fd.png)

problem is also when objectPoolSize is unchanged(10) and .collectionSizeRange(2, 10) and for some run is collectionSize randomized as 10

second problem is that depthLimit is not working in some cases, for example when I set it to 3
EasyRandomParameters().randomizationDepth(3)
                .collectionSizeRange(2, 2)
                .objectPoolSize(2)

![image](https://user-images.githubusercontent.com/2378631/72426460-0826da80-378a-11ea-9146-c01fc31a112e.png)

version
org.jeasy:easy-random-core:4.1.0

**Comment by benas** [comment]
> even with depth=2 is still A.property.prop1 =null and A.property.prop2 =null

This is what depth=2 means (as explained in the [docs](https://github.com/j-easy/easy-random/wiki/Randomization-parameters#randomization-depth)), in your example:

Level 1: A
Level 2: property
Level 3: prop1/prop2

so with depth=2, it's not surprising that prop1/prop2 are null. Those should be non null with depth=3.

> second problem is that depthLimit is not working in some cases, for example when I set it to 3
> EasyRandomParameters().randomizationDepth(3)
> .collectionSizeRange(2, 2)
> .objectPoolSize(2)

What you show in the screenshot does not mean the limit does not work. The limit does not work if you have a `StackOverflowError`. But this is actually IntelliJ recursively showing the content of each nested variable (which happens to become the same instance at some point due to re-using the same cached values). But as you can see, you have:

1. randomizationDepth(3): `A`, `property` and `prop1/prop2` are not null (`prop1/prop2` are not shown in the screenshot but they should not be null with depth=3 as explained previously)
2. collectionSizeRange(2, 2): all `property` lists have size=2 (it is the same instance `ArrayList@6231` actually, but other lists should also have exactly two items in them)
3. objectPoolSize(2): you have only two instance of A, `A@4872` and `A@6138`

So I see nothing wrong with what you shared (which I tested on my side as well). I'm closing this issue for now, but if you still have a question, please add a comment.
