### ISSUE TITLE
XmlGregorianCalendar type not supported

### ISSUE THREAD

**Issue by atrujillofalcon** [j-easy/easy-random#395]
Easy-Random currently don't support XmlGregorianCalendar types.

**Comment by benas** [comment]
That's on purpose, I added a note about that in the [Supported types](https://github.com/j-easy/easy-random/wiki/Supported-types#4-date-and-time-types) section so that it is clearly documented.

The reason is that `javax.xml.datatype` types (namely `Duration` and `XMLGregorianCalendar`) are not easy to deal with:

* they are abstract, 
* they require a factory to be created, 
* they can be easily created in an illegal state,
* etc

and I'm not ready to write/maintain code to randomize them.

You can use custom randomizers for these types.

**Comment by emosrb** [comment]
@benas Can you please share an example of  custom randomizers  for XMLGregorianCalendar

**Comment by odravison** [comment]
I will be glad fo these examples too!

**Comment by odravison** [comment]
Hey guys, I got stuck again with this issue and I solve.
I create a randomizer `XMLGregorianCalendar` and put it on my EasyRandom instance using `EasyRandomParameters` to generate instances of `XMLGregorianCalendar.class`

Below is my code:

My XMLGregorianCalendar randomizer settings:

```
public class XMLGregorianCalendarRandomizer implements Randomizer<XMLGregorianCalendar> {

    @Override
    public XMLGregorianCalendar getRandomValue() {
        try {
            // This will generate a dateTime value with this pattern: 2021-08-06T12:59:39.151Z
            return DatatypeFactory.newInstance()
                    .newXMLGregorianCalendar(
                            (GregorianCalendar) GregorianCalendar.getInstance(TimeZone.getTimeZone(ZoneOffset.UTC))
                    );
        } catch (DatatypeConfigurationException e) {
            e.printStackTrace();
            return null;
        }
    }
}
```

My EasyRandomParameters settings;

```
public static EasyRandom getGenerator() {
        EasyRandomParameters parameters = new EasyRandomParameters()
                .collectionSizeRange(1, 3)
                .randomize(XMLGregorianCalendar.class, new XMLGregorianCalendarRandomizer());
        generator = new EasyRandom(parameters);
        return generator;
    }
```

I hope to this help anyone who need this.
