### ISSUE TITLE
Add Level of Efforts for generating field values

### ISSUE THREAD

**Issue by onacit** [j-easy/easy-random#408]
Anybody would've known that there are plenty of way to excluding fields for being generated with random values.

But a configurable feature of a level-of-efforts will be great.

Say, 

```java
class Some {

    //@NotNull // Should be null with any newly created instances.
    @Id
    private Long id; // DB-side generated

    //@NotNull // Should be null with any newly generated instances.
    @ManyToOne
    private Some parent;
}
```

I found EasyRandom tries to generate the `parent` field (so much recursively) and my single instance has a very big object tree.

Can I have 

* A chance to know for (existing way) of avoiding non-mandatory fields as null?
* A chance to know for an optional feature of effort?

**Comment by benas** [comment]
I believe there is no need for a new feature to achieve that. A combination of [object-pool-size](https://github.com/j-easy/easy-random/wiki/Randomization-parameters#object-pool-size) and [randomization-depth](https://github.com/j-easy/easy-random/wiki/Randomization-parameters#randomization-depth) parameters along with custom randomizers should do it. Otherwise, you can provide a custom `ObjectFactory` that implements that "level of effort".

I'm closing this issue for now, but feel free to add a comment if you need more support on that.
