### ISSUE TITLE
Enhance documentation of Bean Validation constraint parameters precedence

### ISSUE THREAD

**Issue by soulsreaver666** [j-easy/easy-random#447]
In case a get method for some List in the objects is annotated with : 
@Size(min=1)   public List<Address> getAddresses() {
    return addresses;
  }

Easy random do not take into consideration collection size limitation I provide : 
EasyRandomParameters parameters = new EasyRandomParameters()
            .seed(random.nextLong())
            .randomizationDepth(2)
            .collectionSizeRange(1, 4)
            .overrideDefaultInitialization(true);

 BusinessPartner businessPartner; = new EasyRandom(parameters).nextObject(BusinessPartner.class);

and generates really long list

![image](https://user-images.githubusercontent.com/74959109/100985732-9778e000-354c-11eb-82bd-b17398eaae0e.png)

Is there a way to limitate such kind of list ?

**Comment by murdos** [comment]
@soulsreaver666 : I don't think there's a way with current released versions.

I'll soon push a PR that allows that, by attempting to reduce range from `@Size` annotation, using collectionSizeRange from EasyRandomParameters.

**Comment by soulsreaver666** [comment]
Great. Just let me know

**Comment by benas** [comment]
> In case a get method for some List in the objects is annotated with @SiZe(min=1) .. Easy random do not take into consideration collection size limitation I provide

This is the expected behaviour which is documented (but not clearly) in the [bean validation](https://github.com/j-easy/easy-random/wiki/bean-validation-support) section of the wiki, see:

```
Heads up: Bean validation constraints will take precedence over ...
```

I will update the wiki to make this more explicit. So Bean Validation annotation parameters take precedence over global parameters, otherwise Easy Random will generate **invalid** data, which would obviously be incorrect. Here is a test case that shows the expected behaviour:

```java
@Test
void beanValidationParametersShouldTakePrecedenceOverGlobalParameters() {
    // given
    class Person {
        @Size(min = 15, max = 20)
        private List<String> names;
    }
    EasyRandomParameters parameters = new EasyRandomParameters().collectionSizeRange(1, 10);
    EasyRandom easyRandom = new EasyRandom(parameters);
    
    // when
    Person person = easyRandom.nextObject(Person.class);
    
    // then
    assertThat(person.names.size()).isBetween(15, 20);
}
```

In your case, the range from the `@Size` annotation is [1, 255] (the max defaults to 255), that's why ER generates a value (241) in that range and not in the [1, 4] range from the `collectionSizeRange` parameter.

> Is there a way to limitate such kind of list ?

The simplest way would be adding a `max` attribute to the `@Size` annotation. Otherwise, if you can't modify the class, you can use a custom randomizer for that field, something like:

```java
@Test
void customRandomizersShouldTakePrecedenceOverBeanValidationConstraints() {
    // given
    class Person {
        @Size(min = 15, max = 20)
        private List<String> names;
    }
    int randomIntInRange = new IntegerRangeRandomizer(1, 10).getRandomValue();
    EasyRandomParameters parameters = new EasyRandomParameters()
            .randomize(FieldPredicates.named("names").and(FieldPredicates.inClass(Person.class)), new ListRandomizer<>(new StringRandomizer(), randomIntInRange));
    EasyRandom easyRandom = new EasyRandom(parameters);
    
    // when
    Person person = easyRandom.nextObject(Person.class);
    
    // then
    assertThat(person.names.size()).isBetween(1, 10);
}
```

@murdos  As shown previously, custom randomizers are the way to go if one knows what he/she is doing and wants to override the BV constraints (even though I would not do that because this goes against what the class designer intended). So I believe there is no need for changing the code here, it's a documentation issue and I will enhance the wiki accordingly. Thank you for the follow up anyway!

**Comment by benas** [comment]
> I will update the wiki to make this more explicit.

I updated the documentation with more details and a complete example: https://github.com/j-easy/easy-random/wiki/bean-validation-support#bean-validation-contraint-parameters-precedence.

Hopefully this is clear enough now.

**Comment by murdos** [comment]
@benas : it's a shame, I think it should and could work out of the box.
For the reference here's my modified code: https://github.com/j-easy/easy-random/compare/master...murdos:fix/447

It includes changes from https://github.com/j-easy/easy-random/pull/448, that's why I was waiting before pushing it.

**Comment by soulsreaver666** [comment]
> In your case, the range from the `@Size` annotation is [1, 255] (the max defaults to 255), that's why ER generates a value (241) in that range and not in the [1, 4] range from the `collectionSizeRange` parameter.

I understand your point of view but maybe it will be good to have a possibility to change this default 255, because in our case the object we want to generate is really complex, and using custom randomizers for each field will not be efficient. Because in our object there is a lot of list of different object types and right now generating random object takes even 5 minutes. So maybe it will be good to have the possibility to change 255 default value, so in cases Size max annotation is not present, new default value will be taken

**Comment by benas** [comment]
@murdos 

> It computes the intersection between BV range and ER parameters range, and uses it to generates valid data.

We shouldn't be doing any computation. It's exactly that kind of smartness that should be avoided to keep things simple, stupid. It's only a matter of precedence here: BV takes precedence, and this can be overridden with custom randomizers if needed as shown in my previous comment or a custom `BeanValidationAnnotationHandler`.

@soulsreaver666 

The default max of 255 came from #360 to make it consistent with JPA. You did not mention if you are able to simply add the `max` attribute or not. Adding a parameter to configure the default values of `@Size` attribute means we need to add other parameters for the default values of the attributes of `@Min`, `@Max`, etc, which does not make sense. If you can't add the `max` attribute to the class because you can't modify it and can't use custom randomizers neither because you have a lot of fields, then you can ultimately provide a custom `BeanValidationAnnotationHandler` which will be applied to the whole object graph (you can find an example in this [test](https://github.com/j-easy/easy-random/blob/370d2f3bc03bcb5f9d9ddd030b3b05cd63c984e8/easy-random-bean-validation/src/test/java/org/jeasy/random/validation/BeanValidationTest.java#L249)).
