### ISSUE TITLE
Bean validation randomization with multiple annotations

### ISSUE THREAD

**Issue by devoto13** [j-easy/easy-random#455]
Not sure if this is a bug report, a feature request, or just needs to be documented as a known limitation.

Consider the below bean:

```
public class CredentialsView {
    @NotBlank
    @Size(max = 256)
    @Email
    public String email;

    public CredentialsView() {}
}
```

`BeanValidationRandomizerRegistry` will [iterate over a map](https://github.com/j-easy/easy-random/blob/master/easy-random-bean-validation/src/main/java/org/jeasy/random/validation/BeanValidationRandomizerRegistry.java#L75) of supported annotations and use the first matching randomizer. Note that the order of iteration is not defined because it is a map. As a result, it may first pick a `NotBlank` randomizer, which expectedly fails the `Email` (an potentially `Size`) validator down the road.

I understand that it is not possible to combine validators, but maybe it is worth giving supported annotations an explicit ordering, so more specific annotations will be checked first. I'm particularly thinking about `Email` -> `Size` -> `NotBlank` ordering, but maybe there are other cases where ordering makes sense.

Is it something you're willing to integrate into the library? Or is it better to implement in a custom registry?

**Comment by iBavtovich** [comment]
Would like also raise a topic of using `LinkedHashMap` instead of just `HashMap` in the `BeanValidationRandomizerRegistry`. It is clear and documented, that handling multiple validation annotations is out of the scope of this lib. But having this uncertainty in the order, cause that generated with the same `seed` objects with more than one annotation will be different. This breaks pseudorandomness of the library.

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. As mentioned by @iBavtovich , combining validation annotations is out of the scope of ER. Using a custom randomizer/registry is the way to go for this requirement. I understand that the issue here is _not_ about combining validators but rather about ordering. But even for ordering, things can get quite complex very quickly, and the ordering can be subjective. Moreover, the combination of validation annotations can be incorrect in the first place (something like `@Null @Size(max = 1) @Email private String email;` or `@Past @Future private Date birthDate;`), before even talking about ordering.. and I am not sure ER can or should detect that.

For these reasons, I am closing this issue.

That said, Bean Validation support will be discontinued anyway starting from v6, see #499. If you are interested in maintaining that module as a separate extension, please let me know and I will add a reference to it in the README. The feature requested here can be added to that extension. Otherwise, the code of the module can be copied in the project using it and the feature can be implemented in the copy.
